language: node_js
node_js:
  - 12
dist: xenial
services:
  - xvfb

install:
  - npm install
script:
  - npm run validate

deploy:
  provider: npm
  email: '$NPM_EMAIL'
  api_key: '$NPM_TOKEN'
  skip_cleanup: true
  on:
    tags: true
